### ISSUE TITLE
pending_change相关逻辑有问题

### ISSUE THREAD

**Issue by bluebore** [bluebore/bfs#116]
每次nameserver重启时，都会把所有的block标记为pending_change=false
但这些block中可能有些正在被写入，写入完成后FinishBlock调用MarkBlockStable会导致assert失败

**Comment by yvxiang** [comment]
那SetBlockVersion时需要持久化一下

**Comment by yvxiang** [comment]
#117

**Comment by bluebore** [comment]
感觉是两个问题，
version持久化这个确实需要，但之前怎么工作了，我先理理。。。

**Comment by yvxiang** [comment]
已查清：在ns处理BlockReport时，如果发现当前副本数与期望副本数不符，便会将block状态改为pending_change 这样，在ns重启后，block的pending_change先被改为了false，然后第一个副本report时，由于ns检查到副本数不够，便又改回了pending_change为true，导致可以正常工作，而如果block较多，刚好在ns重启和cs BlockReport之间插入了Close，便会assert失败。
