### ISSUE TITLE
GetChunkServerChains会返回dead的cs

### ISSUE THREAD

**Issue by yvxiang** [bluebore/bfs#148]
在两个DeadCheck之间插入GetChunkServerChains时可能返回dead的cs

**Comment by bluebore** [comment]
两次deadcheck之间为什么会有chunkserver超时呢？

**Comment by yvxiang** [comment]
GetChunkServerChains和DeadCheck要加同一把锁，可能GetChunkServerChains把DeadCheck挤在了后面

**Comment by yvxiang** [comment]
不过其实也不在这一会儿，即使ns返回的是正常的cs，SDK那边还是可能连不上
