### ISSUE TITLE
 正常写情况下，判断IsComplete和CloseBlock的时机有问题

### ISSUE THREAD

**Issue by yvxiang** [bluebore/bfs#182]
`LocalWriteBlock`里，会先调用`Block::Write()`将数据包放入sliding window，然后调用`IsComplete`判断是不是所有数据包已经都从sliding window中取出，如果是，将会调用`CloseBlock`将文件描述符关闭，同步元信息。而实际上，`IsComplete`并不一定会在对某一个数据包执行`LocalWriteBlock`时成立。

**Comment by bluebore** [comment]
你是觉得当前有问题还是 @lylei 的pr #181 有问题啊

**Comment by yvxiang** [comment]
当前有问题

**Comment by bluebore** [comment]
最后一个LocalWriteBlock时肯定成立啊，因为最后一个肯定会触发slidingwindow的Notify，然后检查IsComplete

**Comment by yvxiang** [comment]
slidingwindow的Notify是按包的顺序来的，如果最后一个包之前的几个包卡了呢？

**Comment by lylei** [comment]
滑动窗口是乱序进顺序出的，时间上最后一个调用Notify的并不一定是文件顺序上的最后一个，但是这时候文件顺序上的最后一个包肯定已经到了。。不知道说明白了没。。确实有点绕==

**Comment by yvxiang** [comment]
想通了。从LocalWriteBlock到SlidingWindow::Add到Notify再到Block::Append这一条链中没有异步调用，这样就没问题了。
我的错。。。
