### ISSUE TITLE
chunkserver挂掉后

### ISSUE THREAD

**Issue by bluebore** [bluebore/bfs#61]
1. close和sync长期不返回，初步判断是重试时间间隔太长，5次，每次一分钟
2. 副本恢复存在问题

**Comment by linyvxiang** [comment]
我先测试一下。

**Comment by bluebore** [comment]
第二个sandbox就能测出来，触发死循环

**Comment by linyvxiang** [comment]
问题已查明，在于每pull完一个block后，目的端不会向nameserver报告，即使pull完所有block，也只是向nameserver报告pull完成，并没有更新该block的replica列表，实际的更新操作在目的端的下一次block report中进行。这样，在这个间隙中可能再次向目的端重复发送pull同一个block的命令。
#62已将其修复

**Comment by linyvxiang** [comment]
commit 0099c6b3da0533de22bcf076840ff1e2177a5ea7 修正了一个bug，这个bug将导致chunkserver链中后续结点挂掉后不能反映给前面节点，不知道和你描述的是否相关，不过好像不太会使close过慢。
我再继续测试一下。

**Comment by bluebore** [comment]
应该已经不存在了
