### ISSUE TITLE
nameserver元数据存储

### ISSUE THREAD

**Issue by yvxiang** [bluebore/bfs#68]
当前nameserver中元数据是存储在本地磁盘上的，是否有必要将其以其它方式进行存储，比如存到ins中去，后面便可以同时起多个nameserver?

**Comment by bluebore** [comment]
嗯，正准备这么搞，但nameserver数据量太大，不知道ins能不能扛得住

**Comment by linyvxiang** [comment]
我先试着弄一下~

**Comment by yvxiang** [comment]
pr已年久失修，可以参考[https://github.com/yvxiang/dfs/tree/store_meta_data_in_ins](url)这个分支
