### ISSUE TITLE
分批block report问题

### ISSUE THREAD

**Issue by yvxiang** [bluebore/bfs#70]
对于block副本数的维持，当前作法是　副本数小于要求 & 不处于第一轮block report　时，会发送pull block请求。
当初这样做的考虑是，如果不等待一段时间，那么由于chunkserver启动的先后顺序不同，有可能会造成不必要的副本复制。
但是，分批进行block report之后，这样也有问题了。因为每个chunkserver每次只汇报部分block，当chunkserver连接到新的master时，还是很可能会导致一些不必要的复制操作。
目前想到了三种方法：
1. chunkserver连接到nameserver时，先作一轮完整的汇报，后续汇报分批
2. nameserver等所有新连接过来的chunkserver都至少进行过一轮完整的汇报后，再考虑对副本数不足的块进行复制
3. 直接让nameserver启动后等待一段时间再允许复制

**Comment by bluebore** [comment]
现在用的不就是第一种么。。。
实时上这个分批汇报的方式我部署的时候都是关闭的，即把每批大小设为int_max
原因不是你上面说的问题，而是当block多了，会导致汇报一轮要很久，很多已经删除的block无法及时清理（现在block清理依赖report）。
副本恢复和GC这块我近期我打算重新理下。

**Comment by linyvxiang** [comment]
当前连接上nameserver后，并没有作完整的汇报，直接分批了。而且在nameserver端的逻辑是，第一次汇报时不考虑复制，而不是第一轮汇报时。

**Comment by yvxiang** [comment]
已经有safemode去解决了
