### ISSUE TITLE
chunkserver选择逻辑

### ISSUE THREAD

**Issue by bluebore** [bluebore/bfs#78]
当前新block选择chunkserver的逻辑是“按数据量加权的随机化”，即：选择哪个chunkserver是随机的，每个chunkserver都可能被选中，但数据量越小的chunkserver被选中的概率越大。
由于并没有考虑chunkserver的负载，当数据量小的chunkserver磁盘io被打满后，会拖慢整个集群。

**Comment by linyvxiang** [comment]
我想起了GFS的论文中好像提到过这种情况，印象中是除了考虑负载外，还要限制 "每个chunkserver最近一段时间内创建的文件数量"

**Comment by bluebore** [comment]
嗯，但那个不解决现在的问题，现在的问题是这台机器磁盘就是比其他机器稍慢点。。。
这个估计不好解决，我在这只是记录下，以后慢慢想解决方案。

**Comment by bluebore** [comment]
使用FLAGS_chunkserver_max_pending_buffers进行了限制保证chunkserver不会被写打满，读的问题后续解决
