### ISSUE TITLE
副本恢复

### ISSUE THREAD

**Issue by yvxiang** [bluebore/bfs#84]
副本恢复有必要做吗？好像这不是一件太容易的事……

**Comment by lylei** [comment]
1. 当前副本恢复数据结构pulling_chunkservers为block到cs得映射。拟改为cs到block得映射。
  原因：集群规模大的情况下，一个block被report一次的周期太长，不利于副本快速恢复。
2. 添加后台扫描全量mapping，把需要恢复的block加到恢复队列。
  好处：保证不漏副本。
  问题：1）mapping结构要加锁，有潜在性能问题。
                  方案：
扫描周期随数据量增长。
